# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0004_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='terapeutas',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
