# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0005_auto_20161213_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
