# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0006_terapeuta_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitulacionAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('centro', models.CharField(blank=True, max_length=256, null=True)),
                ('localidad', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='titulaciones',
            field=models.ManyToManyField(to='terapeutas.TitulacionAux'),
        ),
    ]
