# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(blank=True, max_length=256)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('direccion', models.CharField(max_length=256)),
            ],
        ),
    ]
