# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peciente',
            new_name='Paciente',
        ),
    ]
