# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0003_auto_20161123_2116'),
        ('pacientes', '0004_paciente_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_ini', models.TimeField(null=True)),
                ('hora_fin', models.TimeField(null=True)),
                ('info', models.TextField()),
                ('doc', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('terapeutas', models.ManyToManyField(to='terapeutas.Terapeuta')),
            ],
        ),
    ]
