# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(blank=True, max_length=256)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pacientes.Tutor'),
            preserve_default=False,
        ),
    ]
