# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_remove_paciente_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Tutor'),
            preserve_default=False,
        ),
    ]
