# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_auto_20170210_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='tutor',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
