# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_auto_20170210_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
    ]
