# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0018_paciente_terapeutas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPacienteAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=128, null=True)),
                ('descripcion_estado', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.EstadoPacienteAux'),
        ),
    ]
