# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0020_auto_20170219_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tutores'),
        ),
    ]
