# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0005_auto_20161213_0703'),
        ('pacientes', '0005_sesion'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglasHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('dias', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábados'), ('D', 'Domingos')], max_length=9)),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('terapeutas', models.ManyToManyField(to='terapeutas.Terapeuta')),
            ],
        ),
    ]
