# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_reglashorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglashorario',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reglashorario',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
