# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_auto_20161213_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábados'), ('D', 'Domingos')], max_length=9)),
                ('laborable', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reglashorario',
            name='dias',
        ),
        migrations.AddField(
            model_name='reglashorario',
            name='dias',
            field=models.ManyToManyField(to='horario.DiasAux'),
        ),
    ]
