# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_auto_20170210_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglashorario',
            name='dias',
        ),
        migrations.AddField(
            model_name='reglashorario',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.DiasAux'),
        ),
    ]
